# Generated by Django 4.1.1 on 2022-10-01 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_custmer_id_order_custmer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='custmer',
            new_name='customer',
        ),
    ]
